name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  http: ^0.13.6
  image_picker: ^1.1.1
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.7
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  url_strategy: ^0.3.0
  universal_html: ^2.2.4
  image: ^4.1.7
  flutter_widget_from_html_core: ^0.8.5+3
  country_code_picker: ^3.2.0
  flutter_typeahead: ^5.2.0
  fwfh_selectable_text: ^0.8.3+1
  circular_countdown_timer: ^0.2.3
  timezone: ^0.9.3
  marquee: ^2.2.3
  flutter_inappwebview: ^6.1.5
  audioplayers: ^6.0.0
  flutter_facebook_auth: ^5.0.6
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  share_plus: ^10.1.3
  expandable_bottom_sheet: ^1.1.1+1
  scroll_to_index: ^3.0.1
 
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  just_the_tooltip: ^0.0.12
  sign_in_with_apple: ^6.1.0
  mobile_scanner: ^6.0.6
  app_links: ^6.0.2
  go_router: 12.1.3
  firebase_auth: ^5.4.0
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^5.0.6
  animated_custom_dropdown: ^3.1.1
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.0.0
  drift: ^2.25.0
  drift_flutter: ^0.2.4
  cached_network_image_platform_interface:
  collection: any
 

dev_dependencies:
  flutter_lints: ^4.0.0
  fwfh_text_style: ^2.23.8
  drift_dev: ^2.25.1
  build_runner: ^2.4.13

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/json/
    - assets/payment/
    - assets/
    - web/assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400